In [1]:
import numpy as np
import pandas as pd

In [2]:
gdp = pd.read_csv("../data/raw/gdp_growth.csv").rename(columns={'value' : 'gdp_growth'})
cap = pd.read_csv('../data/raw/capital.csv').rename(columns={'value' : 'capital'})
exp = pd.read_csv('../data/raw/exports.csv').rename(columns={'value' : 'exports'})
fdi = pd.read_csv('../data/raw/fdi.csv').rename(columns={'value' : 'fdi'})
gov = pd.read_csv('../data/raw/gov_final.csv').rename(columns={'value' : 'govt'})
imp = pd.read_csv('../data/raw/imports.csv').rename(columns={'value' : 'imports'})
inf = pd.read_csv('../data/raw/inflation.csv').rename(columns={'value' : 'inf'})
pop = pd.read_csv('../data/raw/population.csv').rename(columns={'value' : 'pop'})
ump = pd.read_csv('../data/raw/unemployment.csv').rename(columns={'value' : 'ump'})

In [3]:
gdp.head()

                       country countryiso3code  date  gdp_growth
0  Africa Eastern and Southern             AFE  2025    3.743016
1  Africa Eastern and Southern             AFE  2024    2.787931
2  Africa Eastern and Southern             AFE  2023    1.941382
3  Africa Eastern and Southern             AFE  2022    3.668029
4  Africa Eastern and Southern             AFE  2021    4.452643

In [4]:
cap.head()

                       country countryiso3code  date    capital
0  Africa Eastern and Southern             AFE  2025  18.192575
1  Africa Eastern and Southern             AFE  2024  18.509686
2  Africa Eastern and Southern             AFE  2023  19.843989
3  Africa Eastern and Southern             AFE  2022  20.460209
4  Africa Eastern and Southern             AFE  2021  19.643056

In [5]:
exp.head()

                       country countryiso3code  date    exports
0  Africa Eastern and Southern             AFE  2025  25.566559
1  Africa Eastern and Southern             AFE  2024  25.521582
2  Africa Eastern and Southern             AFE  2023  26.160466
3  Africa Eastern and Southern             AFE  2022  27.033079
4  Africa Eastern and Southern             AFE  2021  25.728269

In [6]:
fdi.head()

                       country countryiso3code  date       fdi
0  Africa Eastern and Southern             AFE  2025       NaN
1  Africa Eastern and Southern             AFE  2024  2.142273
2  Africa Eastern and Southern             AFE  2023  1.962269
3  Africa Eastern and Southern             AFE  2022  1.721400
4  Africa Eastern and Southern             AFE  2021  4.917338

In [7]:
gov.head()

                       country countryiso3code  date       govt
0  Africa Eastern and Southern             AFE  2025  14.858760
1  Africa Eastern and Southern             AFE  2024  14.845353
2  Africa Eastern and Southern             AFE  2023  15.065154
3  Africa Eastern and Southern             AFE  2022  15.473983
4  Africa Eastern and Southern             AFE  2021  15.345453

In [8]:
imp.head()

                       country countryiso3code  date    imports
0  Africa Eastern and Southern             AFE  2025  27.785399
1  Africa Eastern and Southern             AFE  2024  28.305737
2  Africa Eastern and Southern             AFE  2023  29.503507
3  Africa Eastern and Southern             AFE  2022  29.472460
4  Africa Eastern and Southern             AFE  2021  26.288167

In [9]:
inf.head()

                       country countryiso3code  date        inf
0  Africa Eastern and Southern             AFE  2025   4.270111
1  Africa Eastern and Southern             AFE  2024   4.770857
2  Africa Eastern and Southern             AFE  2023   7.399186
3  Africa Eastern and Southern             AFE  2022  10.883478
4  Africa Eastern and Southern             AFE  2021   6.824727

In [10]:
pop.head()

                       country countryiso3code  date       pop
0  Africa Eastern and Southern             AFE  2025  2.511278
1  Africa Eastern and Southern             AFE  2024  2.472801
2  Africa Eastern and Southern             AFE  2023  2.519167
3  Africa Eastern and Southern             AFE  2022  2.592754
4  Africa Eastern and Southern             AFE  2021  2.649439

In [11]:
ump.head()

                       country countryiso3code  date       ump
0  Africa Eastern and Southern             AFE  2025  7.539233
1  Africa Eastern and Southern             AFE  2024  7.571697
2  Africa Eastern and Southern             AFE  2023  7.676548
3  Africa Eastern and Southern             AFE  2022  7.869470
4  Africa Eastern and Southern             AFE  2021  8.407412

In [12]:
# GDP base dataframe
df = gdp.copy()

# Merge remaining datasets
df = df.merge(
    inf[["country", "date", "inf"]],
    on=["country", "date"],
    how="left"
)

df = df.merge(
    ump[["country", "date", "ump"]],
    on=["country", "date"],
    how="left"
)

df = df.merge(
    pop[["country", "date", "pop"]],
    on=["country", "date"],
    how="left"
)

df = df.merge(
    exp[["country", "date", "exports"]],
    on=["country", "date"],
    how="left"
)

df = df.merge(
    imp[["country", "date", "imports"]],
    on=["country", "date"],
    how="left"
)

df = df.merge(
    fdi[["country", "date", "fdi"]],
    on=["country", "date"],
    how="left"
)

df = df.merge(
    cap[["country", "date", "capital"]],
    on=["country", "date"],
    how="left"
)

df = df.merge(
    gov[["country", "date", "govt"]],
    on=["country", "date"],
    how="left"
)

In [13]:
df.head()

,country,countryiso3code,date,gdp_growth,inf,ump,pop,exports,imports,fdi,capital,govt
0,Africa Eastern and Southern,AFE,2025,3.743016,4.270111,7.539233,2.511278,25.566559,27.785399,NaN,18.192575,14.858760
1,Africa Eastern and Southern,AFE,2024,2.787931,4.770857,7.571697,2.472801,25.521582,28.305737,2.142273,18.509686,14.845353
2,Africa Eastern and Southern,AFE,2023,1.941382,7.399186,7.676548,2.519167,26.160466,29.503507,1.962269,19.843989,15.065154
3,Africa Eastern and Southern,AFE,2022,3.668029,10.883478,7.869470,2.592754,27.033079,29.472460,1.721400,20.460209,15.473983
4,Africa Eastern and Southern,AFE,2021,4.452643,6.824727,8.407412,2.649439,25.728269,26.288167,4.917338,19.643056,15.345453

In [14]:
df.shape

(17490, 12)

In [15]:
df.isna().sum()

country               0
countryiso3code     330
date                  0
gdp_growth         3169
inf                6018
ump                9314
pop                 362
exports            6100
imports            6048
fdi                5753
capital            6569
govt               6428
dtype: int64

In [16]:
df["country"].nunique()

265

In [17]:
import requests

# Fetch country metadata to identify aggregates
url = "http://api.worldbank.org/v2/country?format=json&per_page=400"
resp = requests.get(url).json()
countries_meta = resp[1]

meta_df = pd.DataFrame([{
    'countryiso3code': c['id'],
    'region': c['region']['value']
} for c in countries_meta])

aggregates = meta_df[meta_df['region'] == 'Aggregates']['countryiso3code'].tolist()

# Check what's in your data
found_aggregates = df[df['countryiso3code'].isin(aggregates)]['country'].unique()
print(f"Aggregates found in df ({len(found_aggregates)}):")
print(found_aggregates)

# Filter them out
df = df[~df['countryiso3code'].isin(aggregates)].reset_index(drop=True)

print(f"\nShape after filtering: {df.shape}")
print(f"Unique countries after: {df['country'].nunique()}")

Aggregates found in df (43):
['Africa Eastern and Southern' 'Africa Western and Central' 'Arab World'
 'Caribbean small states' 'Central Europe and the Baltics'
 'Early-demographic dividend' 'East Asia & Pacific'
 'East Asia & Pacific (excluding high income)'
 'East Asia & Pacific (IDA & IBRD countries)' 'Euro area'
 'Europe & Central Asia' 'Europe & Central Asia (excluding high income)'
 'Europe & Central Asia (IDA & IBRD countries)' 'European Union'
 'Heavily indebted poor countries (HIPC)' 'IBRD only' 'IDA & IBRD total'
 'IDA blend' 'IDA only' 'IDA total' 'Late-demographic dividend'
 'Latin America & Caribbean'
 'Latin America & Caribbean (excluding high income)'
 'Latin America & the Caribbean (IDA & IBRD countries)'
 'Least developed countries: UN classification' 'Low & middle income'
 'Middle East, North Africa, Afghanistan & Pakistan'
 'Middle East, North Africa, Afghanistan & Pakistan (excluding high income)'
 'Middle East, North Africa, Afghanistan & Pakistan (IDA & IBRD)'
 'Middle income' 'North America' 'OECD members' 'Other small states'
 'Pacific island small states' 'Post-demographic dividend'
 'Pre-demographic dividend' 'Small states' 'South Asia'
 'South Asia (IDA & IBRD)' 'Sub-Saharan Africa'
 'Sub-Saharan Africa (excluding high income)'
 'Sub-Saharan Africa (IDA & IBRD countries)' 'World']

Shape after filtering: (14652, 12)
Unique countries after: 222

In [19]:
import pandas as pd

df = pd.read_csv('../data/processed/finale.csv')  # your file is actually CSV format despite the .xls name
print(f"Shape before: {df.shape}")
print(f"Unique countries before: {df['country'].nunique()}")

# These are the leftover aggregates — income groups + not classified
unwanted_categories = [
    'High income', 'Upper middle income', 'Lower middle income', 
    'Low income', 'Middle income', 'Low & middle income',
    'Not classified'
]

df_clean = df[~df['country'].isin(unwanted_categories)].reset_index(drop=True)

print(f"\nShape after: {df_clean.shape}")
print(f"Unique countries after: {df_clean['country'].nunique()}")

# Confirm they're gone
remaining_unwanted = df_clean[df_clean['country'].isin(unwanted_categories)]
print(f"\nUnwanted rows remaining (should be 0): {len(remaining_unwanted)}")

df_clean.to_csv('finale_clean.csv', index=False)

Shape before: (14652, 12)
Unique countries before: 222

Shape after: (14322, 12)
Unique countries after: 217

Unwanted rows remaining (should be 0): 0